from enum import StrEnum


class TemperatureClass(StrEnum):
    AMBIENT = "AMBIENT"
    CHILLED = "CHILLED"
    FROZEN = "FROZEN"


class HandlingClass(StrEnum):
    STANDARD = "STANDARD"
    HAZ = "HAZ"
    HRV = "HRV"
    PRODUCE = "PRODUCE"
    DAMAGE = "DAMAGE"
    SPECIAL = "SPECIAL"


class LocationKind(StrEnum):
    STORAGE = "STORAGE"
    UNPACK = "UNPACK"
    DAMAGE = "DAMAGE"
    SPECIAL = "SPECIAL"
    STAGE = "STAGE"


class AssociateState(StrEnum):
    OFFLINE = "OFFLINE"
    WAITING = "WAITING"
    OFFERED = "OFFERED"
    PICKING = "PICKING"
    PACKING_RACKING = "PACKING_RACKING"
    BREAK = "BREAK"
    OTHER_ACTIVITY = "OTHER_ACTIVITY"


class TaskState(StrEnum):
    READY = "READY"
    OFFERED = "OFFERED"
    PICKING = "PICKING"
    PACKING_RACKING = "PACKING_RACKING"
    STAGED = "STAGED"
    HANDED_OFF = "HANDED_OFF"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"


class OrderState(StrEnum):
    CREATED = "CREATED"
    ALLOCATED = "ALLOCATED"
    PICKING = "PICKING"
    PICKED = "PICKED"
    STAGED = "STAGED"
    HANDED_OFF = "HANDED_OFF"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"


class ScanStatus(StrEnum):
    COMMITTED = "COMMITTED"
    DUPLICATE = "DUPLICATE"
    REJECTED = "REJECTED"


class DowntimeKind(StrEnum):
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    DEVICE_RECOVERY = "DEVICE_RECOVERY"
    SYSTEM_EXCEPTION = "SYSTEM_EXCEPTION"
